[build.env]
passthrough = [
    "PKG_CONFIG_PATH",
    "LD_LIBRARY_PATH",
    "PKG_CONFIG_ALLOW_CROSS",
]

[target.aarch64-unknown-linux-gnu]
image = "xobs/aarch64-unknown-linux-gnu"

[target.arm-unknown-linux-gnueabi]
image = "xobs/arm-unknown-linux-gnueabi"

[target.powerpc-unknown-linux-gnu]
image = "xobs/powerpc-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
image = "xobs/x86_64-unknown-linux-gnu"

[target.x86_64-pc-windows-gnu]
image = "xobs/x86_64-pc-windows-gnu"